doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Board:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Board/Entity'
                prefix: 'App\Model\Board\Entity'
                alias: Board
            Message:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Message/Entity'
                prefix: 'App\Model\Message\Entity'
                alias: Message
            Thread:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Thread/Entity'
                prefix: 'App\Model\Thread\Entity'
                alias: Thread
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User